from . syntax_kind import SyntaxKind
from utils.ie_numberable import IEnumerable


class Lexer:

    def __init__(self, text: str) -> None: ...

    def __peek(self, offset: int) -> chr: ...

    def lex(self) -> SyntaxKind: ...

    def next(self) -> None: ...

    @property
    def diagnostics(self) -> IEnumerable: ...

    @property
    def current(self) -> chr: ...
